# cat syslogNG-output.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGOutput
metadata:
  name: syslog-output
  namespace: quickstart
spec:
  elasticsearch:
    url: "https://devops87.ef.com/es/_bulk"
    index: "expertflow"
    type: ""
    user: "elastic"
    tls:
      peer_verify: false
#      ssl_version: "TLSv1_2"
    password:
      valueFrom:
        secretKeyRef:
          name: elastic
          key: password
# kubectl -n quickstart create secret generic elastic --from-literal=password=Elastic123
